### ISSUE TITLE
Repo license

### ISSUE THREAD

**Issue by OBrezhniev** [vocdoni/zk-voceremony#140]
Hello @lucasmenendez, @altergui!

We at Polygon ID really liked how you did the ceremony (I've participated) and would like to run our own based on your code.

If you are okay with that, is it possible to add license to the repository?

Best regards,
Oleksandr
Polygon ID

**Comment by lucasmenendez** [comment]
@OBrezhniev 

Done! If you need anything, please do not hesitate to contact us!

Thanks!

**Comment by OBrezhniev** [comment]
Thank you very much @lucasmenendez!
